### ISSUE TITLE
яндекс карты геокодер

### ISSUE THREAD

**Issue by igorancho** [gruy/crm#1]
![image](https://user-images.githubusercontent.com/54850688/146920970-03167ce0-516a-4c3b-861d-c0b3a0ad575f.png)

1. [ ]

**Comment by gruy** [comment]
Если платный аккаунт в Яндексе не вариант, то нужно переходить на другой сервис карт, например Openstreetmap.
Ограничения тоже есть, но все данные можно накопить у себя, а с картой Яндекса так не получится.
Но нужно все-равно проверять.

**Comment by igorancho** [comment]
ещё Алексей в первом файле правок советовал кэширование использовать. и яндекс сам об этом пишет: Обратите внимание: чтобы одинаковые обращения к геокодеру не считались несколько раз, запросы можно кэшировать на срок до 30 дней. Кэширование также уменьшит нагрузку на ваш сайт или приложение.

**Comment by gruy** [comment]
Кэширование я сделал и оно работает.
На данный момент (за 9 ней) из 1780 запросов из кэша сработало 620.

**Comment by igorancho** [comment]
кудаже тысяча сжирается, это надо тогда дождаться когда опять будет сбой и смотреть что в тот момент делали?может им запрос в тех поддержку написать? только сформулируй вопрос а я могу отправить

**Comment by igorancho** [comment]
пока я января вроде ошибок не было, значит кэш помогает. но какйо у него предел. может подумать всё таки о накоплении данных у себя? или как лучше?

**Comment by gruy** [comment]
Сейчас эти данные и так хранятся на сервере, только в отдельной базе.
