### ISSUE TITLE
Не все поверхности попадают в задачи монтажнику

### ISSUE THREAD

**Issue by gruy** [gruy/crm#14]
Центральный район  сделал заказ 1054, а в задачи к монтажнику прилетело в замену 990 и в ремонт 37, итого 1027, 27 штук где-то потерялись.

http://nadomofone.ru/client/order/3607/
http://nadomofone.ru/task/6458/
http://nadomofone.ru/task/6459/

На повреждённые стенды делаем отдельно задачу на ремонт, но даже с ремонтной задачей получилось общее количество меньше.

Там ещё некое ограничение по-моему стояло типа не возможно на один день сделать и задачу на  замену и задачу на ремонт, может из-за этого?

**Comment by gruy** [comment]
Получается сейчас так:

- при создании задачи по клиенту сохраняются только неповрежденные поверхности
- при создании задачи на ремонт: если дата совпадает с датой другой задачи в том же районе (если есть хотя бы один адрес для работы) в список на ремонт (в одну дату с основной работой) попадают только те дома/поверхности, где в доме все поверхности повреждены

В принципе, соответствует алгоритму, только нужно запретить создавать задачу на ремонт в этот же день

**Comment by igorancho** [comment]
всё работает
