### ISSUE TITLE
поисковик по улице в заказе

### ISSUE THREAD

**Issue by igorancho** [gruy/crm#16]

**Comment by igorancho** [comment]
не сразу нашёл поисковую строку, под район нельзя её сделать?
сам поиск не работает пока

**Comment by gruy** [comment]
Он ищет по всем словам в таблице.
Если не работает, то может нужно сбросить кэш браузера обновив всю страницу (Ctrl+F5)

**Comment by igorancho** [comment]
обновил кэш, автоматом не даёт подходящие, на энтер нажимаю не ищет
и всётаки снизу она не удобно расположена, наверху никак её не разместить?

**Comment by gruy** [comment]
Может я не правильно понял - нужно искать не в таблице списка заказа, а в форме адресов для заказа?
Т.е. кроме района добавить улицу?

**Comment by igorancho** [comment]
![image](https://user-images.githubusercontent.com/54850688/161001524-6d534333-f833-4566-b43c-fd381621e2a4.png)
тут вроде написано введите адрес. да поиск нужен по адресам когда создаёшь заказ, вываливается много адресов и иногда сложно найти какойто

**Comment by gruy** [comment]
Фильтр по улице добавлен.

**Comment by igorancho** [comment]
изначально думал про поисковую строку и подборку улицы, но так  как сейчас сделали тоже думаю будет достаточно удобно, оставляем так

**Comment by igorancho** [comment]
всё таки как они у нас сортируются в заказе(номера домов)
здесь идут вразнобой http://nadomofone.ru/client/order/3704/

**Comment by gruy** [comment]
Сортировку добавил.

**Comment by igorancho** [comment]
отлично, работает
