### ISSUE TITLE
старая проблема с занятостью по клиентам

### ISSUE THREAD

**Issue by igorancho** [gruy/crm#3]
продолжает вываливать в новый  заказ к другому клиенту, уже занятые адреса:
сделал заказ в продаже мтс=мтс_спартановка с 28.12 по 22.01, занял 73 подъездов.
 следом делаю заказ  впродаже домру=домру_спартановка с 28.12 по 22.01 и он мне высыпает ВСЕ адреса спартановки(450) как свободные, хотя 73 уже заняты.
пытался менять дату начала периода, дату конца периода-не помогает
выбрал в заказ дом который уже занят- сохранил, он сохранился
в поверхностях выбрал этот дом, он показывает его как занятый, в графе клиент прочерк.
сделал заказ в продаже пауэрнет, также с 28.12 по 22.01, выбрал адреса с принадлежностью к УК Афина (137п), сохранил.
тпереь в продаже домру в заказ домру_спарта вываливает 313 (т.е. 450-137) получается пауэрнетовские адреса занялись, а мтс совские адреса так и вываливает как свободные.
сделал заказ домру спарта в продаже домру с 28.12.по **23.01**. также вывалил мне 313 свободных, вручную выбрал реально свободные, сохранил. захожу в поверхности, делаю фильтрацию спартановка\свободные=он мне вываливает 73подъезда(которые реально заняты мтс.
пересохранил у мтс дату окончания заказа вместо 22.01.=23.01= занялись, в поверхностях свободных не показывает...
сейчас родилась мысль, не завязан ли наш алгорит на недели? январь растянут у нас на шесть недель, 22.01 это конец четвёртой недели, а 23.01.это уже пятая неделя. но так это не должно быть
таже фигня по 7 ветров, сделал заказ мтс с 28.12 по 22.01., делаю заказ домру с 28.12 по 22.01 он мне вываливает как свободные адреса занятые мтс. пресохранил заказ мтс 7ветровс 28.12. по 23.01.  снова делаю заказ домру с 28.12 по22.01./по 23.01 вроде перестал вываливать занятые, вываливает только свободные.
т.е. именно на первого клиента программа както ориентируется, если до 22.01 занимаешь, она их даёт другим, еслидо 23.01 то вроде не даёт дургим их занимать. хрень какая то.
таже фигня с пуэрнетом по 7 ветрах у него тоже с 28.12 до 22.01 размещение, делаю у заказа домру теже даты,мне вываливаются как свободные занятыен пауэрнетом адреса.
но например поселок водстрой который тоже занят с 27.12 до 22.01, он другим клиентам не вываливает его адреса  в заказ как свободные. в поверхностях пишет их как занятые, но в графе клиент стоит прочерк, хотя в предыдущем месяце никто их не занимал (оычно прочерк рисует когда два разных клиента один за одним размещаются, что тоже не удобно.

по жилгороду сделал мтс с 28.12 по 22.01. и для домру с 28.12.по 22.01 вывалил для домру только реально свободные адреса!

**Comment by gruy** [comment]
Исправлено в #11
