### ISSUE TITLE
старая проблема: не работает фильтр поверхности занятость в заданную дату

### ISSUE THREAD

**Issue by igorancho** [gruy/crm#4]

**Comment by gruy** [comment]
Переделал фильтрацию.

Старая фильтрация вообще не учитывала то, что могут быть свободные промежутки, могут быть заказы в будущем, которые не давали возможность показывать, что есть свободные диапазоны до этого заказа и т.п.

Фильтрация по занятости вообще не имеет смысла без указания даты - теперь она всегда присутствует, по умолчанию показывает на текущий день.
