### ISSUE TITLE
не то превью фото в истории поверхности

### ISSUE THREAD

**Issue by igorancho** [gruy/crm#5]
в превью в истории поверхности показывается старое фото, если кликаешь на него то открывается новое(реальное)
а сегодня обнаружил что по старым датам показывает тоже старое превью, а когда кликаешь на него то показывает новую фотку(последнее размещение.
например дымченко 18А, кликаю на фотку от 8апреля, открывается декабрьская фотка, кликаю на фотку от 17 сентября открывается декабрьская фотка

**Comment by gruy** [comment]
При удалении старых записей и фотографий иногда происходила рассинхронизация (или из-за нехватки места на диске) и фотографии записывались только под названием адреса.
Добавил в имя файла в конец случайную строку, чтобы имена всегда были уникальными.
