### ISSUE TITLE
Обновление списка клиентов в фильтре

### ISSUE THREAD

**Issue by gruy** [gruy/crm#8]
Обновлять список клиентов в фильтре при изменении даты начала или окончания поиска.

**Comment by igorancho** [comment]
у нас должна правильно считаться работа
в смысле стоимость работы реальной, если например монтажник сделал монтаж, то ему вместо замены(как установлено в задаче) считается монтаж
здесь осмотр не отображается
http://nadomofone.ru/adjuster/1/payment/

**Comment by igorancho** [comment]
список обновляется
